# Jekyll設定ファイル
# 詳細は以下リンク先を参照
# https://just-the-docs.github.io/just-the-docs/docs/configuration

##############################
# 全般

# ページ概要
title: CoffeeRoasterSet Docs
description: This is the Documents of CoffeeRoasterSet, gimmic assets for the VRChat sold on the Booth.
theme: just-the-docs

# 掲載ページのURL指定
url: https://denkihitsujikobo.github.io
repository: DenkiHitsujiKobo/CoffeeSystem-Docs  # TODO: あとでリポジトリ名を修正

# 各ページのパーマリンク生成方法を指定
permalink: pretty


##############################
# ページ構成

# デフォルトのページ構成を指定
defaults:
  - scope:
      path: "docs/"
      type: "pages"
    values:
      layout: "default"

# ページ右上の常設リンク定義
aux_links:
  "Booth - 電気羊工房": "https://cultnhut.booth.pm"
aux_links_new_tab: true

# サイドバーの有効化
nav_enabled: true

# カラーテーマ
color_scheme: green

# フキダシの色指定
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


##############################
# システム関係

# 検索の設定
search_enabled: true
search:
  # 検索にかかる見出しレベル
  heading_level: 2

  # 検索結果のプレビュー数
  previews: 2

  # 検索にヒットした単語の、前後に出る単語数
  preview_words_before: 2
  preview_words_after: 2

  # 検索の区切り文字定義
  tokenizer_separator: /[\s/]+/

  # 検索結果にURLを出すか
  rel_url: true

  # ページ右下に検索ボタンをつけるかどうか
  button: false

  # 検索欄へのショートカットキー
  focus_shortcut_key: "k"

# 図形描画ライブラリmermaidの設定
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# ページ構成に含めないファイルの指定
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-jtd.md
  - README.md
  - repo-docs/
